export type XiXamCategory = 'tương' | 'bất' | 'liêu' | 'cải';

export interface XiXamLot {
  id: number;
  name: string;
  han: string;
  meaning: string;
  category: XiXamCategory;
}

export const XI_XAM_LOTS: XiXamLot[] = [
  { id: 1, name: 'Thượng thượng', han: '上上', meaning: 'Mọi sự suôn sẻ, tốt lành an yên, không lo sợ, tiến bộ rõ rệt, may mắn đầy đủ.', category: 'tương' },
  { id: 2, name: 'Thượng thượng lợi', han: '上上利', meaning: 'Rất thuận lợi cho mọi công việc, đặc biệt hợp với các việc kinh doanh, buôn bán lợi nhuận cao.', category: 'tương' },
  { id: 3, name: 'Thượng', han: '上', meaning: 'Công việc tiến triển tốt, may mắn không quá lớn nhưng ổn định, phù hợp với những người cần nhẫn nại.', category: 'tương' },
  { id: 4, name: 'Thượng lợi', han: '上利', meaning: 'May mắn vừa phải, công việc chậm rồi nhanh, cần phải kiên nhẫn chờ đợi rồi mới có kết quả.', category: 'tương' },
  { id: 5, name: 'Trung', han: '中', meaning: 'Tính cách không tốt không xấu, mọi việc chừa ở giữa, không quá cao cũng không quá thấp.', category: 'bất' },
  { id: 6, name: 'Trung bình', han: '中平', meaning: 'Mọi sự vừa phải, không tốt không xấu, phải nỗ lực hơn để có được kết quả tốt.', category: 'bất' },
  { id: 7, name: 'Trung lợi', han: '中利', meaning: 'Công việc có cơ hội tốt, nhưng cần tìm kiếm cách khác để thành công, thách thức sẽ xuất hiện.', category: 'bất' },
  { id: 8, name: 'Trung bất', han: '中不', meaning: 'Kết quả không rõ ràng, có lúc tốt có lúc không, cần chuẩn bị cho tình huống xấu nhất.', category: 'bất' },
  { id: 9, name: 'Hạ', han: '下', meaning: 'Mọi sự khó khăn, gặp trở ngại, cần phải cẩn thận từ từ mới có thể vượt qua.', category: 'liêu' },
  { id: 10, name: 'Hạ hạ', han: '下下', meaning: 'Rất xui xẻo, những khó khăn to lớn sắp đến, cần để tâm linh nữu thận để tránh được họa.', category: 'liêu' },
  { id: 11, name: 'Hạ nhưng chuyển được', han: '下轉', meaning: 'Hiện tại khó khăn nhưng sẽ có cơ hội quay ngược, cần kiên nhẫn và chờ đợi.', category: 'cải' },
  { id: 12, name: 'Hạ nhưng yên', han: '下但安', meaning: 'Khó khăn nhưng yên tĩnh, không nên vội vàng mà phải chờ thời cơ thích hợp.', category: 'cải' },
  { id: 13, name: 'Lợi', han: '利', meaning: 'Được lợi đủ đầy, mọi việc tiến triển tốt, may mắn có đủ để sống yên bình.', category: 'tương' },
  { id: 14, name: 'Lợi lợi', han: '利利', meaning: 'Cực kỳ có lợi, mọi sự thuận lợi tối đa, không còn gì phải lo lắng nữa.', category: 'tương' },
  { id: 15, name: 'Lợi ít', han: '利少', meaning: 'Có lợi nhưng không nhiều, cần phải chăm chỉ làm việc mới có được thêm lợi nhuận.', category: 'bất' },
  { id: 16, name: 'Bất lợi', han: '不利', meaning: 'Không thuận lợi cho mọi công việc, nên để ý đến những vấn đề nhỏ để tránh thảm họa.', category: 'liêu' },
  { id: 17, name: 'Bất', han: '不', meaning: 'Mọi sự không như ý muốn, gặp chướng ngại dọc đường, cần kiên nhẫn vượt qua.', category: 'liêu' },
  { id: 18, name: 'Bất tốt', han: '不好', meaning: 'Tính chất không tốt, sẽ gặp rắc rối, nên cẩn thận trong mọi công việc.', category: 'liêu' },
  { id: 19, name: 'Bất bất', han: '不不', meaning: 'Vô cùng xui xẻo, tất cả đều bất thành công, phải tìm cách thay đổi hệ thống.', category: 'liêu' },
  { id: 20, name: 'Bất lợi nhưng may', han: '不利但吉', meaning: 'Tuy không thuận lợi nhưng còn may mắn, sẽ có cơ hội thoát khỏi khó khăn.', category: 'cải' },
  { id: 21, name: 'Tốt lành', han: '吉', meaning: 'Công việc sẽ tốt lành, không gặp bất kỳ trở ngại gì, mọi sự như ý.', category: 'tương' },
  { id: 22, name: 'Tốt lành tốt lành', han: '吉吉', meaning: 'Cực kỳ tốt lành, tinh thần phấn khích, may mắn đến từ khắp nơi.', category: 'tương' },
  { id: 23, name: 'Tốt lành vừa phải', han: '吉平', meaning: 'Tốt lành nhưng mức độ vừa phải, không quá cao nhưng cũng an toàn.', category: 'tương' },
  { id: 24, name: 'Tốt hơn xấu', han: '吉勝凶', meaning: 'May mắn nhiều hơn xui xẻo, sự tốt lành sẽ chiếm ưu thế.', category: 'tương' },
  { id: 25, name: 'Xấu', han: '凶', meaning: 'Gặp phải sự xui xẻo, cần phải chuẩn bị tinh thần để vượt qua.', category: 'liêu' },
  { id: 26, name: 'Xấu xấu', han: '凶凶', meaning: 'Cực kỳ xui xẻo, những rắc rối lớn sắp xảy ra, cần rất thận trọng.', category: 'liêu' },
  { id: 27, name: 'Xấu nhưng tránh được', han: '凶但可避', meaning: 'Xui xẻo nhưng có thể tránh được, nếu cẩn thận sẽ không ảnh hưởng.', category: 'cải' },
  { id: 28, name: 'Xấu chuyển tốt', han: '凶轉吉', meaning: 'Hiện tại xui xẻo nhưng sẽ chuyển thành tốt lành, cần kiên nhẫn chờ đợi.', category: 'cải' },
  { id: 29, name: 'Trung', han: '中', meaning: 'Mọi sự không rõ ràng, cần phải tìm kiếm cách tốt nhất để tiến triển.', category: 'bất' },
  { id: 30, name: 'Trung bất', han: '中不', meaning: 'Kết quả không chắc chắn, có thể tốt hoặc xấu, cần chuẩn bị cho hai trường hợp.', category: 'bất' },
  { id: 31, name: 'Có tốt có xấu', han: '有吉有凶', meaning: 'May mắn và xui xẻo xen kẽ nhau, cần phải bình tĩnh để xử lý từng tình huống.', category: 'bất' },
  { id: 32, name: 'Vừa tốt vừa xấu', han: '半吉半凶', meaning: 'Một nửa tốt một nửa xấu, kết quả phụ thuộc vào cách hành động của bạn.', category: 'bất' },
  { id: 33, name: 'Sắp tốt', han: '將吉', meaning: 'Sắp sửa sẽ gặp điều tốt lành, chỉ cần chờ thêm một lúc nữa.', category: 'cải' },
  { id: 34, name: 'Sắp xấu', han: '將凶', meaning: 'Sắp sửa sẽ gặp khó khăn, cần chuẩn bị tâm thế để đối mặt.', category: 'liêu' },
  { id: 35, name: 'Rất tốt', han: '極吉', meaning: 'Cực kỳ tốt lành, không gì tốt hơn, mọi sự hoàn toàn như ý.', category: 'tương' },
  { id: 36, name: 'Rất xấu', han: '極凶', meaning: 'Cực kỳ xui xẻo, cần phải rất thận trọng và may mắn để tránh thảm họa.', category: 'liêu' },
  { id: 37, name: 'Tốt nhưng cần cẩn', han: '吉但慎', meaning: 'Tốt lành nhưng vẫn cần phải thận trọng, không nên chủ quan.', category: 'tương' },
  { id: 38, name: 'Xấu nhưng không quá', han: '凶但不極', meaning: 'Xui xẻo nhưng không phải cực độ, vẫn còn cơ hội để quay ngược.', category: 'cải' },
  { id: 39, name: 'Như ý', han: '如意', meaning: 'Mọi sự như ý muốn, không gặp trở ngại, tiến triển suôn sẻ.', category: 'tương' },
  { id: 40, name: 'Không như ý', han: '不如意', meaning: 'Mọi sự không như ý muốn, cần phải điều chỉnh kế hoạch.', category: 'liêu' },
  { id: 41, name: 'Yên bình', han: '安平', meaning: 'Yên bình và bình thường, không có gì đặc biệt tốt hoặc xấu.', category: 'bất' },
  { id: 42, name: 'Bất yên', han: '不安', meaning: 'Tâm lý không yên tĩnh, sẽ gặp những thay đổi không lường trước được.', category: 'liêu' },
  { id: 43, name: 'Rõ ràng', han: '明', meaning: 'Mọi sự rõ ràng, không có bí ẩn, tiến triển theo đúng kế hoạch.', category: 'tương' },
  { id: 44, name: 'Mờ ám', han: '暗', meaning: 'Mọi sự mờ ám, cần phải tìm tòi để hiểu rõ vấn đề.', category: 'liêu' },
  { id: 45, name: 'Sáng sủa', han: '亮', meaning: 'Tương lai sáng sủa, có nhiều cơ hội phía trước, cần nắm bắt.', category: 'tương' },
  { id: 46, name: 'Tối tăm', han: '暗', meaning: 'Tương lai tối tăm, cần phải chú ý đến những điểm yếu.', category: 'liêu' },
  { id: 47, name: 'Thông suốt', han: '通暢', meaning: 'Mọi con đường đều thông thoáng, không có bất cứ chướng ngại nào.', category: 'tương' },
  { id: 48, name: 'Tắc nghẽn', han: '堵塞', meaning: 'Mọi việc tắc nghẽn, cần phải tìm cách khác để vượt qua.', category: 'liêu' },
  { id: 49, name: 'Thăng tiến', han: '昇進', meaning: 'Sự tiến triển rõ rệt, việc tốt sắp xảy ra, ghi danh có hy vọng.', category: 'tương' },
  { id: 50, name: 'Suy thoái', han: '衰退', meaning: 'Sự suy thoái xảy ra, cần phải cảnh báo và tìm cách cứu vãn.', category: 'liêu' },
  { id: 51, name: 'Phát tài', han: '發財', meaning: 'Tiền tài sẽ tăng, có cơ hội kiếm được khoản lợi lớn.', category: 'tương' },
  { id: 52, name: 'Mất tài', han: '失財', meaning: 'Sẽ có nguy hiểm mất mát tài sản, cần phải cẩn thận.', category: 'liêu' },
  { id: 53, name: 'Tình yêu tốt', han: '愛情吉', meaning: 'Tình yêu sẽ thuận lợi, đó là thời điểm tốt để bày tỏ tình cảm.', category: 'tương' },
  { id: 54, name: 'Tình yêu khó', han: '愛情難', meaning: 'Tình yêu gặp khó khăn, cần phải kiên nhẫn và nỗ lực.', category: 'liêu' },
  { id: 55, name: 'Hôn nhân tốt', han: '婚姻吉', meaning: 'Hôn nhân sẽ thành công, đó là thời điểm tốt để kết hôn.', category: 'tương' },
  { id: 56, name: 'Hôn nhân xấu', han: '婚姻凶', meaning: 'Hôn nhân gặp trở ngại, cần phải suy xét kỹ trước khi quyết định.', category: 'liêu' },
  { id: 57, name: 'Sức khỏe tốt', han: '健康吉', meaning: 'Sức khỏe sẽ tốt, không lo ngại về bệnh tật.', category: 'tương' },
  { id: 58, name: 'Sức khỏe yếu', han: '健康弱', meaning: 'Sức khỏe sẽ yếu, cần phải chú ý và điều trị.', category: 'liêu' },
  { id: 59, name: 'Công việc tốt', han: '工作吉', meaning: 'Công việc sẽ tiến triển tốt, có cơ hội được thăng chức.', category: 'tương' },
  { id: 60, name: 'Công việc xấu', han: '工作凶', meaning: 'Công việc sẽ gặp khó khăn, cần phải cẩn thận.', category: 'liêu' },
  { id: 61, name: 'Học tập tốt', han: '學業吉', meaning: 'Học tập sẽ có kết quả tốt, thi cử sẽ đỗ.', category: 'tương' },
  { id: 62, name: 'Học tập khó', han: '學業難', meaning: 'Học tập sẽ gặp khó khăn, cần phải nỗ lực hơn.', category: 'liêu' },
  { id: 63, name: 'Du hành tốt', han: '旅行吉', meaning: 'Du hành sẽ an toàn và vui vẻ, đó là thời điểm tốt để đi.', category: 'tương' },
  { id: 64, name: 'Du hành xấu', han: '旅行凶', meaning: 'Du hành có nguy hiểm, nên hoãn lại hoặc cẩn thận.', category: 'liêu' },
  { id: 65, name: 'Nhà ở tốt', han: '住居吉', meaning: 'Nhà ở sẽ tốt, có cơ hội mua được nhà đẹp.', category: 'tương' },
  { id: 66, name: 'Nhà ở xấu', han: '住居凶', meaning: 'Nhà ở sẽ gặp vấn đề, cần phải sửa chữa hoặc chuyển nhà.', category: 'liêu' },
  { id: 67, name: 'Gia đình tốt', han: '家庭吉', meaning: 'Gia đình sẽ hạnh phúc, mối quan hệ ấm áp.', category: 'tương' },
  { id: 68, name: 'Gia đình xấu', han: '家庭凶', meaning: 'Gia đình sẽ gặp xích mích, cần phải cân bằng lại.', category: 'liêu' },
  { id: 69, name: 'Bạn bè tốt', han: '朋友吉', meaning: 'Bạn bè sẽ gần gũi, có cơ hội gặp được người bạn tốt.', category: 'tương' },
  { id: 70, name: 'Bạn bè xấu', han: '朋友凶', meaning: 'Bạn bè sẽ xa cách, cần phải cảnh báo về những người xung quanh.', category: 'liêu' },
  { id: 71, name: 'Gặp quý nhân', han: '遇貴人', meaning: 'Sẽ gặp được quý nhân giúp đỡ, mọi sự sẽ suôn sẻ.', category: 'tương' },
  { id: 72, name: 'Gặp nhân vật xấu', han: '遇小人', meaning: 'Sẽ gặp được người xấu, cần phải cẩn thận bảo vệ bản thân.', category: 'liêu' },
  { id: 73, name: 'Vận may', han: '好運', meaning: 'Vận may sẽ tới, những điều tốt sẽ xảy ra không ngờ.', category: 'tương' },
  { id: 74, name: 'Vận xui', han: '衰運', meaning: 'Vận xui sắp xảy ra, cần phải chuẩn bị tinh thần.', category: 'liêu' },
  { id: 75, name: 'Tốt rồi tốt', han: '好上加好', meaning: 'Điều tốt sẽ tiếp tục, không còn gì để lo lắng.', category: 'tương' },
  { id: 76, name: 'Xấu rồi xấu', han: '壞上加壞', meaning: 'Điều xấu sẽ tiếp tục xảy ra, cần phải xử lý cấp bách.', category: 'liêu' },
  { id: 77, name: 'Cân bằng', han: '平衡', meaning: 'Mọi sự sẽ cân bằng, tốt và xấu sẽ được hòa hợp.', category: 'bất' },
  { id: 78, name: 'Ngoài dự báo', han: '意外', meaning: 'Sẽ có những việc ngoài dự báo xảy ra, cần sẵn sàng.', category: 'bất' },
  { id: 79, name: 'Chiêu tài', han: '招財', meaning: 'May mắn với tiền tài, các cơ hội kiếm tiền sẽ xuất hiện.', category: 'tương' },
  { id: 80, name: 'Chiêu phúc', han: '招福', meaning: 'May mắn với hạnh phúc, sự tốt lành sẽ đến.', category: 'tương' },
  { id: 81, name: 'Tránh họa', han: '避禍', meaning: 'Có thể tránh được thảm họa, cần cẩn thận tây bộ.', category: 'cải' },
  { id: 82, name: 'Tiêu tai', han: '消災', meaning: 'Tai họa sẽ được tiêu tan, cần phải tiểu tâm.', category: 'cải' },
  { id: 83, name: 'Khai vận', han: '開運', meaning: 'Vận may sẽ được khai mở, mọi cách sẽ thăng tiến.', category: 'tương' },
  { id: 84, name: 'Trữ năng lượng', han: '積蓄', meaning: 'Cần phải tích trữ năng lượng cho tương lai, đừng vội vàng.', category: 'bất' },
  { id: 85, name: 'Chia sẻ may mắn', han: '分享吉運', meaning: 'May mắn sẽ được chia sẻ với mọi người, giúp đỡ người khác.', category: 'tương' },
  { id: 86, name: 'Nhận phúc duyên', han: '受福報', meaning: 'Sẽ nhận được phúc duyên, những việc tốt sẽ đến.', category: 'tương' },
  { id: 87, name: 'Kính cẩn hành động', han: '謹慎行事', meaning: 'Cần phải kính cẩn trong mọi hành động, không chủ quan.', category: 'bất' },
  { id: 88, name: 'Mở lòng chào đón', han: '開心待', meaning: 'Hãy mở lòng chào đón những điều mới, may mắn sẽ đến.', category: 'tương' },
  { id: 89, name: 'Tìm cân bằng', han: '求平衡', meaning: 'Tìm cân bằng giữa công việc và cuộc sống, sự hòa hợp sẽ đến.', category: 'bất' },
  { id: 90, name: 'Phát tâm từ', han: '發心慈', meaning: 'Phát tâm từ bi, giúp đỡ người khác, may mắn sẽ trở lại.', category: 'tương' },
  { id: 91, name: 'Thanh tịnh tâm', han: '清淨心', meaning: 'Giữ tâm thanh tịnh, không sân hận, may mắn sẽ cùng theo.', category: 'tương' },
  { id: 92, name: 'Kiên trì đi tới', han: '堅持進行', meaning: 'Kiên trì đi tới, không bỏ cuộc, thành công sẽ đến.', category: 'tương' },
  { id: 93, name: 'Lắng nghe trí tuệ', han: '聽智慧', meaning: 'Lắng nghe tiếng nói trí tuệ bên trong, sẽ tìm được con đường đúng.', category: 'tương' },
  { id: 94, name: 'Tin tưởng quá trình', han: '信過程', meaning: 'Tin tưởng vào quá trình, kết quả sẽ đến vào đúng lúc.', category: 'tương' },
  { id: 95, name: 'Thả buông lo lắng', han: '放下憂慮', meaning: 'Hãy thả buông lo lắng, bình tĩnh sẽ mang lại giải pháp.', category: 'cải' },
  { id: 96, name: 'Cảm tạ', han: '感謝', meaning: 'Hãy cảm tạ những gì bạn có, may mắn sẽ lại tìm đến.', category: 'tương' },
];

export function getXiXamLot(seed: number): XiXamLot {
  return XI_XAM_LOTS[seed % XI_XAM_LOTS.length];
}

export const CATEGORY_VI: Record<XiXamCategory, string> = {
  tương: 'Tương',
  bất: 'Bất',
  liêu: 'Liêu',
  cải: 'Cải',
};

export const CATEGORY_MEANINGS: Record<XiXamCategory, string> = {
  tương: 'Tốt lành, may mắn',
  bất: 'Trung bình, vừa phải',
  liêu: 'Xui xẻo, không tốt',
  cải: 'Xấu nhưng có thể chuyển tốt',
};
