// This file was generated by Prisma.
// dotenv only needed for local dev (.env file). Render provides env vars natively.
try { require('dotenv/config') } catch { /* production: env vars from platform */ }
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
